-- ========================== DATA TESTING ===============================

-- KAMAR
INSERT INTO KAMAR 
    (ROW_ID_KAMAR, NOMOR_KAMAR, JENIS_KAMAR, HARGA_KAMAR, STATUS_TERSEDIA)
VALUES('', '101', 0, 250000, 0);

INSERT INTO KAMAR 
    (ROW_ID_KAMAR, NOMOR_KAMAR, JENIS_KAMAR, HARGA_KAMAR, STATUS_TERSEDIA)
VALUES('', '201', 0, 250000, 0);

INSERT INTO KAMAR 
    (ROW_ID_KAMAR, NOMOR_KAMAR, JENIS_KAMAR, HARGA_KAMAR, STATUS_TERSEDIA)
VALUES('', '202', 0, 250000, 1);

INSERT INTO KAMAR 
    (ROW_ID_KAMAR, NOMOR_KAMAR, JENIS_KAMAR, HARGA_KAMAR, STATUS_TERSEDIA)
VALUES('', '301', 1, 750000, 1);

INSERT INTO KAMAR 
    (ROW_ID_KAMAR, NOMOR_KAMAR, JENIS_KAMAR, HARGA_KAMAR, STATUS_TERSEDIA)
VALUES('', '302', 1, 750000, 0);

-- FASILITAS
INSERT INTO FASILITAS
    (ROW_ID_FASILITAS, NAMA_FASILITAS, JUMLAH_TERSEDIA, BIAYA_PEMINJAMAN)
VALUES('', 'Handuk', 12, 15000);

INSERT INTO FASILITAS
    (ROW_ID_FASILITAS, NAMA_FASILITAS, JUMLAH_TERSEDIA, BIAYA_PEMINJAMAN)
VALUES('', 'Sabun', 23, 5000);

INSERT INTO FASILITAS
    (ROW_ID_FASILITAS, NAMA_FASILITAS, JUMLAH_TERSEDIA, BIAYA_PEMINJAMAN)
VALUES('', 'Bantal', 35, 10000);

INSERT INTO FASILITAS
    (ROW_ID_FASILITAS, NAMA_FASILITAS, JUMLAH_TERSEDIA, BIAYA_PEMINJAMAN)
VALUES('', 'Guling', 35, 10000);

INSERT INTO FASILITAS
    (ROW_ID_FASILITAS, NAMA_FASILITAS, JUMLAH_TERSEDIA, BIAYA_PEMINJAMAN)
VALUES('', 'Sandal', 20, 30000);


-- TAMU
INSERT INTO TAMU
    (ROW_ID_TAMU, NAMA_TAMU, NOMOR_TELEPON, EMAIL)
VALUES('', 'Winda Angelina Utama', '082233529285', 'WAU959@GMAIL.COM');

INSERT INTO TAMU
    (ROW_ID_TAMU, NAMA_TAMU, NOMOR_TELEPON, EMAIL)
VALUES('', 'Bambang Budiman', '082212345678', 'BAMBANG123@GMAIL.COM');

INSERT INTO TAMU
    (ROW_ID_TAMU, NAMA_TAMU, NOMOR_TELEPON, EMAIL)
VALUES('', 'Hasan Kasusra', '07059834070', 'hasanksei@gmail.com');

INSERT INTO TAMU
    (ROW_ID_TAMU, NAMA_TAMU, NOMOR_TELEPON, EMAIL)
VALUES('', 'Vanya Malika', '09496591326', 'vanyni@gmail.com');

INSERT INTO TAMU
    (ROW_ID_TAMU, NAMA_TAMU, NOMOR_TELEPON, EMAIL)
VALUES('', 'Karen Nasyiah', '04391040047', 'kareah@gmail.com');


-- H_BOOKING : ada data checkout
INSERT INTO H_BOOKING
    (ROW_ID_BOOKING, ROW_ID_TAMU, JUMLAH_KAMAR_SINGLE, JUMLAH_KAMAR_FAMILY,
    TANGGAL_CHECK_IN, TANGGAL_CHECK_OUT, STATUS_BOOKING, SUBTOTAL,
    BIAYA_TAMBAHAN, KETERANGAN, TOTAL_HARGA)
VALUES 
    ('', 1, 0, 0, 
    to_date('21/03/2017 13:04:08','dd/MM/yyyy hh24:mi:ss'), 
    to_date('23/03/2017 11:05:08','dd/MM/yyyy hh24:mi:ss'), 1, 500000,
    150000, 'merusak shower', 650000);

INSERT INTO H_BOOKING
    (ROW_ID_BOOKING, ROW_ID_TAMU, JUMLAH_KAMAR_SINGLE, JUMLAH_KAMAR_FAMILY,
    TANGGAL_CHECK_IN, TANGGAL_CHECK_OUT, STATUS_BOOKING, SUBTOTAL,
    BIAYA_TAMBAHAN, KETERANGAN, TOTAL_HARGA)
VALUES 
    ('', 2, 2, 0, 
    to_date('21/03/2017 13:04:08','dd/MM/yyyy hh24:mi:ss'), 
    to_date('23/03/2017 11:05:08','dd/MM/yyyy hh24:mi:ss'), 2, 2000000,
    0, '', 2000000);


-- H_BOOKING : tanpa data checkout
INSERT INTO H_BOOKING
    (ROW_ID_BOOKING, ROW_ID_TAMU, JUMLAH_KAMAR_SINGLE, JUMLAH_KAMAR_FAMILY,
    TANGGAL_CHECK_IN, STATUS_BOOKING)
VALUES 
    ('', 3, 2, 0, 
    to_date('21/03/2017 13:04:08','dd/MM/yyyy hh24:mi:ss'), 0);

INSERT INTO H_BOOKING
    (ROW_ID_BOOKING, ROW_ID_TAMU, JUMLAH_KAMAR_SINGLE, JUMLAH_KAMAR_FAMILY,
    TANGGAL_CHECK_IN, STATUS_BOOKING)
VALUES 
    ('', 4, 2, 0, 
    to_date('21/03/2017 13:04:08','dd/MM/yyyy hh24:mi:ss'), 0);


-- D_BOOKING_KAMAR
INSERT INTO D_BOOKING_KAMAR
    (ROW_ID_BOOKING, ROW_ID_KAMAR)
VALUES(1, 1);

INSERT INTO D_BOOKING_KAMAR
    (ROW_ID_BOOKING, ROW_ID_KAMAR)
VALUES(1, 2);

INSERT INTO D_BOOKING_KAMAR
    (ROW_ID_BOOKING, ROW_ID_KAMAR)
VALUES(3, 5);


-- D_BOOKING_FASILITAS
INSERT INTO D_BOOKING_FASILITAS
    (ROW_ID_BOOKING, ROW_ID_FASILITAS, ROW_ID_KAMAR,
    JUMLAH_PEMINJAMAN, BIAYA_PEMINJAMAN, SUBTOTAL)
VALUES(1, 1, 1, 2, 15000, 15000);

INSERT INTO D_BOOKING_FASILITAS
    (ROW_ID_BOOKING, ROW_ID_FASILITAS, ROW_ID_KAMAR,
    JUMLAH_PEMINJAMAN, BIAYA_PEMINJAMAN, SUBTOTAL)
VALUES(1, 3, 1, 2, 10000, 20000);

INSERT INTO D_BOOKING_FASILITAS
    (ROW_ID_BOOKING, ROW_ID_FASILITAS, ROW_ID_KAMAR,
    JUMLAH_PEMINJAMAN, BIAYA_PEMINJAMAN, SUBTOTAL)
VALUES(1, 4, 1, 2, 10000, 20000);

INSERT INTO D_BOOKING_FASILITAS
    (ROW_ID_BOOKING, ROW_ID_FASILITAS, ROW_ID_KAMAR,
    JUMLAH_PEMINJAMAN, BIAYA_PEMINJAMAN, SUBTOTAL)
VALUES(1, 5, 1, 1, 30000, 30000);

INSERT INTO D_BOOKING_FASILITAS
    (ROW_ID_BOOKING, ROW_ID_FASILITAS, ROW_ID_KAMAR,
    JUMLAH_PEMINJAMAN, BIAYA_PEMINJAMAN, SUBTOTAL)
VALUES(1, 2, 1, 1, 5000, 5000);

commit;
