-- ========================== DATA TESTING ===============================

-- KAMAR
INSERT INTO KAMAR 
    (ROW_ID_KAMAR, NOMOR_KAMAR, JENIS_KAMAR, HARGA_KAMAR, STATUS_TERSEDIA)
VALUES('', '101', 0, 150000, 1);

INSERT INTO KAMAR 
    (ROW_ID_KAMAR, NOMOR_KAMAR, JENIS_KAMAR, HARGA_KAMAR, STATUS_TERSEDIA)
VALUES('', '201', 0, 250000, 0);


-- FASILITAS
INSERT INTO FASILITAS
    (ROW_ID_FASILITAS, NAMA_FASILITAS, JUMLAH_TERSEDIA, BIAYA_PEMINJAMAN)
VALUES('', 'HANDUK', 12, 15000);

INSERT INTO FASILITAS
    (ROW_ID_FASILITAS, NAMA_FASILITAS, JUMLAH_TERSEDIA, BIAYA_PEMINJAMAN)
VALUES('', 'SABUN', 23, 5000);


-- TAMU
INSERT INTO TAMU
    (ROW_ID_TAMU, NAMA_TAMU, NOMOR_TELEPON, EMAIL)
VALUES('', 'WINDA ANGELINA UTAMA', '082233529285', 'WAU959@GMAIL.COM');

INSERT INTO TAMU
    (ROW_ID_TAMU, NAMA_TAMU, NOMOR_TELEPON, EMAIL)
VALUES('', 'BAMBANG BUDIMAN', '082212345678', 'BAMBANG123@GMAIL.COM');


-- H_BOOKING : ada data checkout
INSERT INTO H_BOOKING
    (ROW_ID_BOOKING, ROW_ID_TAMU, JUMLAH_KAMAR_SINGLE, JUMLAH_KAMAR_FAMILY,
    TANGGAL_CHECK_IN, TANGGAL_CHECK_OUT, STATUS_BOOKING, SUBTOTAL,
    BIAYA_TAMBAHAN, KETERANGAN, TOTAL_HARGA)
VALUES 
    ('', 1, 2, 0, 
    to_date('21/03/2017 13:04:08','dd/MM/yyyy hh24:mi:ss'), 
    to_date('23/03/2017 11:05:08','dd/MM/yyyy hh24:mi:ss'), 2, 350000,
    150000, 'merusak shower', 500000);


-- H_BOOKING : tanpa data checkout
INSERT INTO H_BOOKING
    (ROW_ID_BOOKING, ROW_ID_TAMU, JUMLAH_KAMAR_SINGLE, JUMLAH_KAMAR_FAMILY,
    TANGGAL_CHECK_IN, STATUS_BOOKING)
VALUES 
    ('', 2, 2, 0, 
    to_date('21/03/2017 13:04:08','dd/MM/yyyy hh24:mi:ss'), 0);


-- D_BOOKING_KAMAR
INSERT INTO D_BOOKING_KAMAR
    (ROW_ID_BOOKING, ROW_ID_KAMAR)
VALUES(1, 1);

INSERT INTO D_BOOKING_KAMAR
    (ROW_ID_BOOKING, ROW_ID_KAMAR)
VALUES(1, 2);


-- D_BOOKING_FASILITAS
INSERT INTO D_BOOKING_FASILITAS
    (ROW_ID_BOOKING, ROW_ID_FASILITAS, ROW_ID_KAMAR,
    JUMLAH_PEMINJAMAN, BIAYA_PEMINJAMAN, SUBTOTAL)
VALUES(1, 1, 1, 2, 15000, 30000);

INSERT INTO D_BOOKING_FASILITAS
    (ROW_ID_BOOKING, ROW_ID_FASILITAS, ROW_ID_KAMAR,
    JUMLAH_PEMINJAMAN, BIAYA_PEMINJAMAN, SUBTOTAL)
VALUES(1, 2, 2, 2, 5000, 10000);

commit;
